# -*- coding: utf-8 -*-
"""la_fires_v1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMRLGLxoUsC5F4AGmb6QnN-ZaBRXWjOq
"""

import pandas as pd
import matplotlib.pyplot as plt
import folium

map_key = "YOUR_NASA_KEY" #api key
url = f"https://firms.modaps.eosdis.nasa.gov/api/area/csv/{map_key}/VIIRS_SNPP_SP/-118.7121,33.9723,-117.9539,34.3118/5/2025-01-07"

df = pd.read_csv(f"https://firms.modaps.eosdis.nasa.gov/api/area/csv/{map_key}/VIIRS_SNPP_SP/-118.7121,33.9723,-117.9539,34.3118/5/2025-01-07")
print(df.head()) #prints the data

fires = df[df["type"] == 0]
print(len(df))
print(len(fires)) #prints fires

dates = ["2025-01-07", "2025-01-12", "2025-01-17", "2025-01-22", "2025-01-27"]
chunks = []

for date in dates:
    url = f"https://firms.modaps.eosdis.nasa.gov/api/area/csv/{map_key}/VIIRS_SNPP_SP/-118.7121,33.9723,-117.9539,34.3118/5/{date}"
    chunk = pd.read_csv(url)
    chunks.append(chunk) #checks the dates; cycles with the url with the list, "dates"

all_data = pd.concat(chunks, ignore_index=True)
fires = all_data[all_data["type"] == 0]

print(len(all_data)) #prints all data
print(len(fires))

per_day = fires["acq_date"].value_counts().sort_index()
per_day.plot(kind="bar")

plt.title("dates of fire dots")
plt.xlabel("dates") #plot diagram to map out data, checking if it is gud or nah
plt.ylabel("fires (pixels/detections)")
plt.show()

mapp = folium.Map(location=[34.14205, -118.333], zoom_start=10, tiles="Esri.WorldImagery") #map, sateleite

for index, row in fires.iterrows(): #loop to gen the red dots
  if row["acq_date"] == "2025-01-07":
    dot_color = "yellow"
  elif row["acq_date"] == "2025-01-08":
    dot_color = "orange"
  elif row["acq_date"] == "2025-01-09":
    dot_color = "red"
  else:
         dot_color = "darkred"
  folium.CircleMarker(
      location=[row["latitude"], row["longitude"]],
      radius=2,
      color= dot_color #self-explaintory
  ).add_to(mapp)
mapp

